package lmpPackage;
/**
 * This class will do the filtering, will use an adapted version of the data class in the def package
 * @author Ylva
 *
 */
public class SensorThread extends Thread {

	/**
	 * This is the address as stored for the accelerometer on this sensor node
	 */
	private int axlAddress;
	
	/**
	 * This is the address as stored for the gyroscope on this sensor node
	 */
	private int gyrAddress;
	/**
	 * This is the constructor to use, sets the addresses of the sensors on this node
	 * @param addressAxl the address of the accelerometer
	 * @param AddressGyr the address of the gyroscope
	 */
	public SensorThread(int addressAxl, int AddressGyr) {
		super();
		axlAddress = addressAxl;
		gyrAddress = AddressGyr;
	}
	
	/**
	 * AutoGenerated constructor, not necessary but keeping it in in case we need it
	 */
	public SensorThread() {
		super();
	}

	/**
	 * AutoGenerated constructor, not necessary but keeping it in in case we need it
	 * @param arg0 first parameter of super class
	 */
	public SensorThread(Runnable arg0) {
		super(arg0);
	}

	/**
	 * AutoGenerated constructor, not necessary but keeping it in in case we need it
	 * @param arg0 first parameter of super class
	 */
	public SensorThread(String arg0) {
		super(arg0);
	}

	/**
	 * AutoGenerated constructor, not necessary but keeping it in in case we need it
	 * @param arg0 first parameter of super class
	 * @param arg1 second parameter of super class
	 */
	public SensorThread(ThreadGroup arg0, Runnable arg1) {
		super(arg0, arg1);
	}

	/**
	 * AutoGenerated constructor, not necessary but keeping it in in case we need it
	 * @param arg0 first parameter of super class
	 * @param arg1 second parameter of super class
	 */
	public SensorThread(ThreadGroup arg0, String arg1) {
		super(arg0, arg1);
	}

	/**
	 * AutoGenerated constructor, not necessary but keeping it in in case we need it
	 * @param arg0 first parameter of super class
	 * @param arg1 second parameter of super class
	 */
	public SensorThread(Runnable arg0, String arg1) {
		super(arg0, arg1);
	}

	/**
	 * AutoGenerated constructor, not necessary but keeping it in in case we need it
	 * @param arg0 first parameter of super class
	 * @param arg1 second parameter of super class
	 * @param arg2 third parameter of super class
	 */
	public SensorThread(ThreadGroup arg0, Runnable arg1, String arg2) {
		super(arg0, arg1, arg2);
	}
	
	/**
	 * AutoGenerated constructor, not necessary but keeping it in in case we need it
	 * @param arg0 first parameter of super class
	 * @param arg1 second parameter of super class
	 * @param arg2 third parameter of super class
	 * @param arg3 fourth parameter of super class
	 */
	public SensorThread(ThreadGroup arg0, Runnable arg1, String arg2, long arg3) {
		super(arg0, arg1, arg2, arg3);
	}
	/**
	 * This method will manage what this thread needs to do, we will divide this thread in different submethods, for example the one 
	 */
	public void run(){
		if(axlAddress==0||gyrAddress==0){
			System.err.println("|Error|One or more of the address are not set, please set these using the constructor");//This makes sure that there are addresses in the correct place
		}else{
			//The first time it runs it needs to run differently, therefore I will use a while method for all but the first runthough
			
		}
	}

}
